# Generated by Django 6.1.1 on 2026-09-30 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_code',
            field=models.CharField(blank=True, default='', help_text="The person's code in Jivo's HR records, e.g. JIVO1234.", max_length=32, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9][A-Za-z0-9._/-]*$', 'Use letters and digits, optionally with . _ / or -.')]),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_code', ''), _negated=True), fields=('employee_code',), name='users_user_employee_code_unique', violation_error_code='employee_code_taken', violation_error_message='Another user already has this employee code.'),
        ),
    ]
