# Generated by Django 6.1.1 on 2026-09-30 06:58

import django.core.validators
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(help_text="Identifier in tokens' `apps` claim, e.g. `oms`. The application sets the same value as JIVO_AUTH['APP'].", max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9][a-z0-9_-]*$', 'Use lowercase letters, digits, hyphens and underscores.')])),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive applications are left out of new tokens and their API key stops working.')),
                ('api_key_hash', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('api_key_prefix', models.CharField(blank=True, editable=False, help_text='First characters of the current API key, to identify it.', max_length=16)),
                ('api_key_created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('users', models.ManyToManyField(blank=True, help_text='Users who may use this application.', related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
