# Generated by Django 6.1.1 on 2026-09-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='previous_refresh_jti',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usersession',
            name='rotated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
