"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/

Every deployment-specific value comes from the environment; `.env.example`
lists them all.
"""

from pathlib import Path
import os
from datetime import timedelta

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

from config import jwt_keys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


## Load env
load_dotenv(BASE_DIR / ".env")


def env_bool(name, default=False):
    value = os.getenv(name)

    if value is None or value.strip() == "":
        return default

    return value.strip().lower() in ("1", "true", "yes", "on")


def env_list(name, default=""):
    return [
        item.strip()
        for item in os.getenv(name, default).split(",")
        if item.strip()
    ]


def env_int(name, default):
    value = os.getenv(name)

    if value is None or value.strip() == "":
        return default

    try:
        return int(value)
    except ValueError as exc:
        raise ImproperlyConfigured(f"{name} must be an integer.") from exc


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", False)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY must be set when DEBUG is off."
        )

    SECRET_KEY = "django-insecure-development-key"

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", "localhost,127.0.0.1")

# Public base URL of this service, e.g. https://auth.jivo.in. Used for links
# in emails and as the default token issuer, so a wrong value breaks every
# consuming application.
PUBLIC_URL = os.getenv("PUBLIC_URL", "").rstrip("/")

if not PUBLIC_URL:
    if not DEBUG:
        raise ImproperlyConfigured(
            "PUBLIC_URL must be set when DEBUG is off, e.g. "
            "https://auth.jivo.in."
        )

    PUBLIC_URL = "http://localhost:8000"

if not DEBUG and not PUBLIC_URL.startswith("https://"):
    raise ImproperlyConfigured("PUBLIC_URL must be an https:// URL.")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third party
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",

    # Local apps
    "health",
    "users",
    "applications",
    "authentication",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Before CommonMiddleware, so CORS headers are added to its responses.
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = "config.asgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}


# Password hashing
# Argon2 hashes new passwords; the PBKDF2 hashers stay so existing hashes
# still verify and are upgraded to Argon2 on the next successful login.

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
]


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Cache
# In Postgres, so throttle counters are shared by all gunicorn workers
# without Redis. applications/migrations/0002 creates the table.

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "jivo_auth_cache",
    },
}


# Logging
# Everything to stderr, where Docker and gunicorn collect it. 4xx responses
# are left to the access log; 5xx tracebacks are logged here.

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "plain": {
            "format": "{asctime} {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "plain",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("LOG_LEVEL", "INFO"),
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "level": "ERROR",
        },
    },
}


# HTTPS
# Behind a TLS-terminating proxy (Nginx), set TRUST_X_FORWARDED_PROTO so
# Django knows the original request was HTTPS. The proxy must overwrite the
# header (`proxy_set_header X-Forwarded-Proto $scheme;`).

if env_bool("TRUST_X_FORWARDED_PROTO"):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", False)

SECURE_HSTS_SECONDS = env_int("SECURE_HSTS_SECONDS", 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS")
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD")

SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# Origins allowed to submit forms (admin, password pages), e.g.
# https://auth.jivo.in.
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")


# CORS
# Browser apps on other origins that call this API directly, e.g.
# https://oms.jivo.in. Tokens travel in headers, not cookies, so
# credentials are not allowed.

CORS_ALLOWED_ORIGINS = env_list("CORS_ALLOWED_ORIGINS")
CORS_ALLOWED_ORIGIN_REGEXES = env_list("CORS_ALLOWED_ORIGIN_REGEXES")
CORS_URLS_REGEX = r"^/(api/|\.well-known/).*$"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
# EMAIL_BACKEND is "smtp" or "console" (prints emails; the default with
# DEBUG on). The EMAIL_* names are env vars only: Django 6.1 forbids the
# legacy EMAIL_* settings alongside MAILERS.

_email_backend = os.getenv(
    "EMAIL_BACKEND",
    "console" if DEBUG else "smtp",
)

if _email_backend == "smtp":
    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.smtp.EmailBackend",
            "OPTIONS": {
                "host": os.getenv("EMAIL_HOST", "localhost"),
                "port": env_int("EMAIL_PORT", 587),
                "username": os.getenv("EMAIL_HOST_USER", ""),
                "password": os.getenv("EMAIL_HOST_PASSWORD", ""),
                "use_tls": env_bool("EMAIL_USE_TLS", True),
                "use_ssl": env_bool("EMAIL_USE_SSL", False),
                "timeout": env_int("EMAIL_TIMEOUT", 10),
            },
        },
    }
elif _email_backend == "console":
    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.console.EmailBackend",
        },
    }
else:
    raise ImproperlyConfigured('EMAIL_BACKEND must be "smtp" or "console".')

DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "no-reply@localhost",
)

# Local development convenience: forgot-password responses include the
# reset token. Only when emails are printed to the console anyway, so a
# production server started with DEBUG on doesn't hand out reset tokens.
RETURN_RESET_TOKEN_IN_RESPONSE = DEBUG and _email_backend == "console"

# Links in emails. `{token}` is replaced with the single-use token. The
# defaults are the pages this service hosts itself.
PASSWORD_RESET_URL = os.getenv(
    "PASSWORD_RESET_URL",
    f"{PUBLIC_URL}/reset-password/?token={{token}}",
)

EMAIL_VERIFICATION_URL = os.getenv(
    "EMAIL_VERIFICATION_URL",
    f"{PUBLIC_URL}/verify-email/?token={{token}}",
)


# Registration
# Registering never grants access to any application; an admin grants that
# per user. Off by default in production. REGISTRATION_EMAIL_DOMAINS (e.g.
# "jivo.in") limits who can register at all.

REGISTRATION_ENABLED = env_bool("REGISTRATION_ENABLED", DEBUG)

REGISTRATION_EMAIL_DOMAINS = [
    domain.lower().lstrip("@")
    for domain in env_list("REGISTRATION_EMAIL_DOMAINS")
]

# Refuse login until the user has verified their email address, so the
# `email` claim can be trusted (and a domain limit can't be sidestepped by
# registering someone else's address).
REQUIRE_VERIFIED_EMAIL = env_bool("REQUIRE_VERIFIED_EMAIL", True)


REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",

    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],

    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],

    # Views opt into a scoped rate by setting `throttle_scope`. These
    # subclasses identify the end user by the IP a trusted application
    # forwards (see applications/throttling.py).
    "DEFAULT_THROTTLE_CLASSES": [
        "applications.throttling.AnonRateThrottle",
        "applications.throttling.UserRateThrottle",
        "applications.throttling.ScopedRateThrottle",
    ],

    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/min",
        "user": "1000/hour",

        # Per account and client IP, and per client IP.
        "login": "5/min",
        "login_ip": "30/min",

        "forgot_password": "3/min",
        "reset_password": "5/min",
        "register": "5/hour",
        "verify_email": "10/min",
        "resend_verification": "3/min",
        "application": "10000/hour",
    },

    # Number of trusted reverse proxies (e.g. 1 behind Nginx). Throttles and
    # session IPs only trust X-Forwarded-For entries added by those proxies;
    # with 0 the header is ignored and REMOTE_ADDR is used.
    "NUM_PROXIES": env_int("NUM_PROXIES", 0),
}


# JWT
# RS256 (default): signed with a private key, verified by other apps with
# the public key published at /.well-known/jwks.json, so no app can mint
# tokens. HS256: every verifying app holds the shared JWT_SECRET_KEY.

JWT_ALGORITHM = os.getenv("JWT_ALGORITHM", "RS256")

if JWT_ALGORITHM == "RS256":
    JWT_SIGNING_KEY = jwt_keys.load_private_key_pem(BASE_DIR)
    JWT_VERIFYING_KEY = jwt_keys.public_key_pem(JWT_SIGNING_KEY)
    JWT_PUBLIC_JWK = jwt_keys.public_jwk(JWT_VERIFYING_KEY, JWT_ALGORITHM)

elif JWT_ALGORITHM == "HS256":
    JWT_SIGNING_KEY = os.getenv("JWT_SECRET_KEY", "")

    if len(JWT_SIGNING_KEY) < 32:
        raise ImproperlyConfigured(
            "JWT_ALGORITHM is HS256, so JWT_SECRET_KEY must be set to at "
            "least 32 characters."
        )

    JWT_VERIFYING_KEY = ""
    JWT_PUBLIC_JWK = None

else:
    raise ImproperlyConfigured('JWT_ALGORITHM must be "RS256" or "HS256".')


# How long a just-rotated refresh token may be sent again and get the same
# new tokens, e.g. by a client whose refresh response was lost, or by two
# requests racing. Later reuse revokes the session: the token may be stolen.
REFRESH_TOKEN_REUSE_GRACE = timedelta(
    seconds=env_int("JWT_REFRESH_REUSE_GRACE_SECONDS", 30),
)

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=env_int("JWT_ACCESS_TOKEN_LIFETIME_MINUTES", 15),
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=env_int("JWT_REFRESH_TOKEN_LIFETIME_DAYS", 30),
    ),

    # SessionTokenRefreshSerializer always rotates and blacklists.
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,

    "UPDATE_LAST_LOGIN": True,

    "ALGORITHM": JWT_ALGORITHM,
    "SIGNING_KEY": JWT_SIGNING_KEY,
    "VERIFYING_KEY": JWT_VERIFYING_KEY,

    "ISSUER": os.getenv("JWT_ISSUER") or PUBLIC_URL,

    "AUTH_HEADER_TYPES": ("Bearer",),

    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "sub",
}


# Per-endpoint documentation lives in each app's schema.py, built from the
# helpers in config/openapi.py.
SPECTACULAR_SETTINGS = {
    "TITLE": "Jivo Auth API",
    "DESCRIPTION": """
Centralized authentication service for Jivo applications.

## Authentication

1. `POST /api/v1/auth/login/` with email and password returns an **access**
   token and a **refresh** token.
2. Send the access token on protected endpoints as
   `Authorization: Bearer <access token>`. In Swagger UI, click
   **Authorize** and paste the access token.
3. When the access token expires, call `POST /api/v1/auth/refresh/`.
   Refresh tokens rotate, so always store the new refresh token it returns.

Endpoints marked with a lock require an access token or, under
**Applications**, an application API key; all others are public.

## Verifying tokens in other applications

Other Jivo applications verify access tokens locally and don't call this API
on every request. Tokens are signed with RS256; the public key is published
at `/.well-known/jwks.json` and each token names its key in the `kid`
header. Access tokens carry these claims:

* `sub`: the user ID (UUID).
* `email`: the user's email address.
* `apps`: slugs of the applications the user may use. An application must
  reject tokens that don't list its own slug.
* `iss`: this service's public URL.
* `token_type`: `access`. Reject any other value.
* `exp`, `iat`, `jti`: expiry, issue time and token ID.

## Errors

Errors use Django REST Framework's format:

* `{"detail": "..."}` for 401, 403, 404 and 429 responses. Token errors
  also carry a `code`, e.g. `token_not_valid`.
* Validation errors (400) map each field to a list of messages, with
  `non_field_errors` for errors not tied to one field.

## Rate limits

Anonymous clients are limited to 100 requests per minute and authenticated
users to 1000 per hour. Login, registration and password reset endpoints
have stricter limits, noted on each operation. Throttled requests get `429`.
""",
    "VERSION": "1.0.0",

    "SERVE_INCLUDE_SCHEMA": False,

    "SCHEMA_PATH_PREFIX": r"/api/v1",

    # Separate request/response components, so read-only fields don't show
    # up in request bodies (and write-only ones not in responses).
    "COMPONENT_SPLIT_REQUEST": True,

    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
    },

    "TAGS": [
        {
            "name": "Authentication",
            "description": (
                "Log in, refresh and verify tokens, log out, and fetch the "
                "public signing keys."
            ),
        },
        {
            "name": "Sessions",
            "description": (
                "List and revoke the current user's sessions (one per "
                "logged-in device)."
            ),
        },
        {
            "name": "Users",
            "description": (
                "User registration, email verification and profile "
                "management."
            ),
        },
        {
            "name": "Password",
            "description": "Password change and reset operations.",
        },
        {
            "name": "Applications",
            "description": (
                "Server-to-server endpoints for Jivo applications, "
                "authenticated with the application's API key."
            ),
        },
        {
            "name": "Health",
            "description": "Service health endpoints.",
        },
    ],

    # Operations get their security requirement from the view's
    # authentication and permission classes; public views set `auth=[]`.
    # These entries extend the generated components.
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "jwtAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
                "description": (
                    "Access token from `POST /api/v1/auth/login/` or "
                    "`POST /api/v1/auth/refresh/`."
                ),
            },
        },
        "schemas": {
            "ValidationError": {
                "type": "object",
                "description": (
                    "Maps each invalid field to a list of error messages. "
                    "`non_field_errors` holds errors not tied to one field."
                ),
                "additionalProperties": {
                    "type": "array",
                    "items": {
                        "type": "string",
                    },
                },
            },
        },
    },
}

AUTH_USER_MODEL = "users.User"
