# Generated by Django 6.1.1 on 2026-09-30 11:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_cache_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('login_succeeded', 'Signed in'), ('login_failed', 'Sign-in failed'), ('logout', 'Signed out'), ('token_reused', 'Refresh token reused'), ('sessions_revoked', 'Sessions revoked'), ('password_changed', 'Password changed'), ('password_reset_requested', 'Password reset requested'), ('password_reset', 'Password reset'), ('account_created', 'Account created'), ('account_deactivated', 'Account deactivated'), ('account_reactivated', 'Account reactivated'), ('email_verified', 'Email verified'), ('access_granted', 'Application access granted'), ('access_revoked', 'Application access removed'), ('api_key_rotated', 'API key rotated')], max_length=40)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='applications.application')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['type', 'created_at'], name='audit_audit_type_70de08_idx'), models.Index(fields=['user', 'created_at'], name='audit_audit_user_id_39eebe_idx'), models.Index(fields=['ip_address', 'created_at'], name='audit_audit_ip_addr_055926_idx')],
            },
        ),
    ]
